apiVersion: v1
kind: Pod
metadata:
  name: monitor-dataset
spec:
  containers:
    - name: monitor-dataset
      image: docker.io/kovaleskilab/meep:v3_lightning      
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: meep-dataset-v2 
          mountPath: /develop/results
  volumes:
    - name: meep-dataset-v2
      persistentVolumeClaim:
        claimName: meep-dataset-v2

  restartPolicy: Never

